services:
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:8003:6379"
    platform: linux/amd64
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "127.0.0.1:8002:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build: .
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - .:/var/www/src
    command: tail -f /var/www/src/.env
    environment:
      - TIME_ZONE=Etc/GMT+0
